// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Patungan.DataAccess.Contexts;

#nullable disable

namespace Patungan.DataAccess.Migrations
{
    [DbContext(typeof(PatunganDbContext))]
    [Migration("20260228042022_AddTranssactionTypeSeeder")]
    partial class AddTranssactionTypeSeeder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "transaction_nature", new[] { "income", "outcome" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Patungan.DataAccess.Entities.MonthlySummaryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CarriedOver")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<decimal>("EndingBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<decimal>("StartingBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("MonthlySummary", (string)null);
                });

            modelBuilder.Entity("Patungan.DataAccess.Entities.TransactionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("MonthlySummaryId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("TransactionTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MonthlySummaryId");

                    b.HasIndex("TransactionTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Transaction", (string)null);
                });

            modelBuilder.Entity("Patungan.DataAccess.Entities.TransactionTypeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nature")
                        .IsRequired()
                        .HasColumnType("public.transaction_nature");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TransactionType", (string)null);
                });

            modelBuilder.Entity("Patungan.DataAccess.Entities.TransactionTypeTemplateModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nature")
                        .IsRequired()
                        .HasColumnType("public.transaction_nature");

                    b.HasKey("Id");

                    b.ToTable("TransactionTypeTemplate", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Primary monthly income",
                            Name = "Salary",
                            Nature = "income"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Secondary income streams",
                            Name = "Side Hustle",
                            Nature = "income"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            Name = "Investasi",
                            Nature = "income"
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            Name = "Belanja Kebutuhan",
                            Nature = "outcome"
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            Name = "Utilitas",
                            Nature = "outcome"
                        },
                        new
                        {
                            Id = 6,
                            Description = "",
                            Name = "Hiburan",
                            Nature = "outcome"
                        });
                });

            modelBuilder.Entity("Patungan.DataAccess.Entities.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Patungan.DataAccess.Entities.MonthlySummaryModel", b =>
                {
                    b.HasOne("Patungan.DataAccess.Entities.UserModel", "User")
                        .WithMany("MonthlySummaries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Patungan.DataAccess.Entities.TransactionModel", b =>
                {
                    b.HasOne("Patungan.DataAccess.Entities.MonthlySummaryModel", "MonthlySummary")
                        .WithMany("Transactions")
                        .HasForeignKey("MonthlySummaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Patungan.DataAccess.Entities.TransactionTypeModel", "TransactionType")
                        .WithMany("Transactions")
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Patungan.DataAccess.Entities.UserModel", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MonthlySummary");

                    b.Navigation("TransactionType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Patungan.DataAccess.Entities.TransactionTypeModel", b =>
                {
                    b.HasOne("Patungan.DataAccess.Entities.UserModel", "User")
                        .WithMany("TransactionTypes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Patungan.DataAccess.Entities.MonthlySummaryModel", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Patungan.DataAccess.Entities.TransactionTypeModel", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Patungan.DataAccess.Entities.UserModel", b =>
                {
                    b.Navigation("MonthlySummaries");

                    b.Navigation("TransactionTypes");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
